import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
const HTML = path.resolve('C:/Users/yakyu/OneDrive/文档/WONDER LETER/MyWord-v2.html');
const b = await chromium.launch({ headless: true });
const p = await b.newPage();
await p.goto(pathToFileURL(HTML).href, { waitUntil: 'networkidle' });
await p.waitForTimeout(700);
await p.evaluate(() => {
  const ed = document.getElementById('editor');
  ed.innerHTML = '';
  const a = document.createElement('a');
  a.href = normalizeUrl('javascript://%0awindow.__XSS=1');
  a.textContent = 'לחץ כאן';
  a.id = 'xssLink';
  a.style.cssText = 'display:inline-block;padding:20px;font-size:20px;';
  ed.appendChild(a);
});
await p.click('#xssLink', { force: true });
await p.waitForTimeout(600);
const r = await p.evaluate(() => ({ xss: !!window.__XSS, href: document.getElementById('xssLink')?.href, url: location.href.slice(0,60) }));
console.log('REAL CLICK:', JSON.stringify(r));
await b.close();
